export const faculty_details=[
    {'id':1,'name': 'Lindsey Stanley', 'employee_id': 'lindseystanley@college.in', 'branch': 'Mechanical Engineering', 'qualification': 'PhD', 'total_research_papers': 13, 'experience': 34},
    {'id':2,'name': 'Samantha Williams', 'employee_id': 'samanthawilliams@college.in', 'branch': 'Computer Science', 'qualification': 'PhD', 'total_research_papers': 7, 'experience': 34},
    {'id':3,'name': 'Jordan Brown', 'employee_id': 'jordanbrown@college.in', 'branch': 'Biotechnology', 'qualification': 'MTech', 'total_research_papers': 13, 'experience': 37},
    {'id':4,'name': 'Alyssa Jones', 'employee_id': 'alyssajones@college.in', 'branch': 'Electrical Engineering', 'qualification': 'PhD', 'total_research_papers': 36, 'experience': 1},
    {'id':5,'name': 'Diana Turner', 'employee_id': 'dianaturner@college.in', 'branch': 'Biotechnology', 'qualification': 'MTech', 'total_research_papers': 44, 'experience': 24},
    {'id':6 ,'name': 'Jennifer Chavez', 'employee_id': 'jenniferchavez@college.in', 'branch': 'Computer Science', 'qualification': 'PhD', 'total_research_papers': 4, 'experience': 24},
    {'id':7,'name': 'Erin Zimmerman', 'employee_id': 'erinzimmerman@college.in', 'branch': 'Biotechnology', 'qualification': 'PhD', 'total_research_papers': 32, 'experience': 34},
    {'id':8 ,'name': 'Susan Carlson', 'employee_id': 'susancarlson@college.in', 'branch': 'Electrical Engineering', 'qualification': 'MTech', 'total_research_papers': 31, 'experience': 17},
    {'id':9 ,'name': 'Brittney Boyd', 'employee_id': 'brittneyboyd@college.in', 'branch': 'Mechanical Engineering', 'qualification': 'PhD', 'total_research_papers': 29, 'experience': 2},
    {'id':10 ,'name': 'Shawn Melton', 'employee_id': 'shawnmelton@college.in', 'branch': 'Mechanical Engineering', 'qualification': 'MTech', 'total_research_papers': 13, 'experience': 17},
    {'id':11 ,'name': 'David Dougherty', 'employee_id': 'daviddougherty@college.in', 'branch': 'Mechanical Engineering', 'qualification': 'PhD', 'total_research_papers': 20, 'experience': 31},
    {'id':12 ,'name': 'Edward Morris', 'employee_id': 'edwardmorris@college.in', 'branch': 'Biotechnology', 'qualification': 'MTech', 'total_research_papers': 47, 'experience': 11},
    {'id':13 ,'name': 'Barbara Harrison', 'employee_id': 'barbaraharrison@college.in', 'branch': 'Biotechnology', 'qualification': 'MTech', 'total_research_papers': 36, 'experience': 39},
    {'id':14 ,'name': 'Michael King', 'employee_id': 'michaelking@college.in', 'branch': 'Computer Science', 'qualification': 'PhD', 'total_research_papers': 45, 'experience': 31},
    {'id':15 ,'name': 'Robert Delacruz', 'employee_id': 'robertdelacruz@college.in', 'branch': 'Chemical Engineering', 'qualification': 'MTech', 'total_research_papers': 7, 'experience': 14},
    {'id':16 ,'name': 'Joe Rivera', 'employee_id': 'joerivera@college.in', 'branch': 'Computer Science', 'qualification': 'PhD', 'total_research_papers': 47, 'experience': 4},
    {'id':17 ,'name': 'Justin Long', 'employee_id': 'justinlong@college.in', 'branch': 'Computer Science', 'qualification': 'PhD', 'total_research_papers': 24, 'experience': 10},
    {'id':18,'name': 'Molly Myers', 'employee_id': 'mollymyers@college.in', 'branch': 'Civil Engineering', 'qualification': 'MTech', 'total_research_papers': 23, 'experience': 36},
    {'id':19,'name': 'Brad Lewis', 'employee_id': 'bradlewis@college.in', 'branch': 'Civil Engineering', 'qualification': 'MTech', 'total_research_papers': 47, 'experience': 11},
    {'id':20 ,'name': 'Kelly Wu', 'employee_id': 'kellywu@college.in', 'branch': 'Biotechnology', 'qualification': 'PhD', 'total_research_papers': 29, 'experience': 26},
    {'id':21 ,'name': 'James Spencer', 'employee_id': 'jamesspencer@college.in', 'branch': 'Civil Engineering', 'qualification': 'PhD', 'total_research_papers': 50, 'experience': 5},
    {'id':22 ,'name': 'Jennifer Diaz', 'employee_id': 'jenniferdiaz@college.in', 'branch': 'Chemical Engineering', 'qualification': 'PhD', 'total_research_papers': 11, 'experience': 19},
    {'id':23 ,'name': 'Denise Lewis', 'employee_id': 'deniselewis@college.in', 'branch': 'Civil Engineering', 'qualification': 'PhD', 'total_research_papers': 26, 'experience': 36},
    {'id':24 ,'name': 'David Cobb', 'employee_id': 'davidcobb@college.in', 'branch': 'Biotechnology', 'qualification': 'MTech', 'total_research_papers': 3, 'experience': 15},
    {'id':25,'name': 'Jason Schwartz', 'employee_id': 'jasonschwartz@college.in', 'branch': 'Electrical Engineering', 'qualification': 'PhD', 'total_research_papers': 36, 'experience': 8},
]

export const project_details=[
    {
        "grant_id": "G001",
        "title": "Community Health Improvement",
        "description": "A grant to improve health services in underserved communities.",
        "amount": 50000,
        "grantor_organization": "Health and Wellness Foundation",
        "recipient_organization": "Community Health Center",
        "grant_date": "2023-01-15",
        "duration": "1 year",
        "status": "Active"
    },
    {
        "grant_id": "G002",
        "title": "STEM Education Initiative",
        "description": "A grant to promote STEM education in high schools.",
        "amount": 75000,
        "grantor_organization": "Tech Innovators Fund",
        "recipient_organization": "High School Network",
        "grant_date": "2023-03-20",
        "duration": "2 years",
        "status": "Active"
    },
    {
        "grant_id": "G003",
        "title": "Environmental Conservation Project",
        "description": "Funding for conservation projects to protect endangered species.",
        "amount": 120000,
        "grantor_organization": "Green Earth Trust",
        "recipient_organization": "Wildlife Protection Agency",
        "grant_date": "2022-11-05",
        "duration": "3 years",
        "status": "Active"
    },
    {
        "grant_id": "G004",
        "title": "Arts and Culture Program",
        "description": "Support for local arts and culture initiatives.",
        "amount": 30000,
        "grantor_organization": "Cultural Heritage Fund",
        "recipient_organization": "City Arts Council",
        "grant_date": "2023-06-12",
        "duration": "1 year",
        "status": "Pending"
    },
    {
        "grant_id": "G005",
        "title": "Youth Empowerment Grant",
        "description": "Funding for programs that empower youth through education and leadership.",
        "amount": 45000,
        "grantor_organization": "Future Leaders Foundation",
        "recipient_organization": "Youth Development Association",
        "grant_date": "2023-02-28",
        "duration": "2 years",
        "status": "Approved"
    },
    {
        "grant_id": "G006",
        "title": "Technology for Education",
        "description": "Grant to provide technological resources for schools.",
        "amount": 95000,
        "grantor_organization": "Tech for Good Initiative",
        "recipient_organization": "National Education Board",
        "grant_date": "2023-04-01",
        "duration": "3 years",
        "status": "Active"
    },
    {
        "grant_id": "G007",
        "title": "Renewable Energy Research",
        "description": "Support for research in renewable energy technologies.",
        "amount": 150000,
        "grantor_organization": "Energy Innovations Trust",
        "recipient_organization": "University of Science",
        "grant_date": "2022-10-15",
        "duration": "2 years",
        "status": "Active"
    },
    {
        "grant_id": "G008",
        "title": "Local Business Development",
        "description": "Funding to support the development of local small businesses.",
        "amount": 50000,
        "grantor_organization": "Economic Growth Fund",
        "recipient_organization": "City Business Incubator",
        "grant_date": "2023-01-20",
        "duration": "1 year",
        "status": "Pending"
    },
    {
        "grant_id": "G009",
        "title": "Mental Health Awareness",
        "description": "Grant to raise awareness and provide resources for mental health.",
        "amount": 40000,
        "grantor_organization": "Mental Health Foundation",
        "recipient_organization": "Health Support Network",
        "grant_date": "2023-05-10",
        "duration": "1 year",
        "status": "Approved"
    },
    {
        "grant_id": "G010",
        "title": "Clean Water Initiative",
        "description": "Support for projects ensuring access to clean water in rural areas.",
        "amount": 80000,
        "grantor_organization": "Water for All Fund",
        "recipient_organization": "Rural Development Agency",
        "grant_date": "2023-03-15",
        "duration": "2 years",
        "status": "Active"
    },
    {
        "grant_id": "G011",
        "title": "Cultural Heritage Preservation",
        "description": "Funding to preserve cultural heritage sites.",
        "amount": 60000,
        "grantor_organization": "Historical Trust",
        "recipient_organization": "Cultural Preservation Society",
        "grant_date": "2022-12-05",
        "duration": "3 years",
        "status": "Active"
    },
    {
        "grant_id": "G012",
        "title": "Urban Green Spaces",
        "description": "Support for the creation and maintenance of urban green spaces.",
        "amount": 50000,
        "grantor_organization": "Urban Renewal Fund",
        "recipient_organization": "City Parks Association",
        "grant_date": "2023-02-10",
        "duration": "2 years",
        "status": "Pending"
    },
    {
        "grant_id": "G013",
        "title": "Innovative Teaching Methods",
        "description": "Grant to develop and implement innovative teaching methods in schools.",
        "amount": 70000,
        "grantor_organization": "Education Futures Fund",
        "recipient_organization": "National Teaching Academy",
        "grant_date": "2023-04-22",
        "duration": "3 years",
        "status": "Active"
    },
    {
        "grant_id": "G014",
        "title": "Disaster Relief and Recovery",
        "description": "Funding for disaster relief and recovery efforts.",
        "amount": 100000,
        "grantor_organization": "Global Relief Fund",
        "recipient_organization": "Emergency Response Organization",
        "grant_date": "2023-01-30",
        "duration": "1 year",
        "status": "Approved"
    },
    {
        "grant_id": "G015",
        "title": "Agricultural Innovation Grant",
        "description": "Support for innovative projects in agriculture.",
        "amount": 85000,
        "grantor_organization": "AgriTech Fund",
        "recipient_organization": "Farming Innovations Network",
        "grant_date": "2023-05-05",
        "duration": "2 years",
        "status": "Active"
    }
]
